default: &default
  adapter: postgresql
  encoding: utf8
  database: rb_ezcollect
  username: root
  password: root
  host: 127.0.0.1
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "rb_ezcollect"
